service: serverless-rest-api-with-dynamodb

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  profile: "serverless_dict"
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  web:
    handler: serve.serve
    events:
      - http:
          path: /
          method: get
          cors: true


  create:
    handler: definition/create.create
    events:
      - http:
          path: definition
          method: post
          cors: true

  list:
    handler: definition/list.list
    events:
      - http:
          path: definition
          method: get
          cors: true

  get:
    handler: definition/get.get
    events:
      - http:
          path: definition/{id}
          method: get
          cors: true

  update:
    handler: definition/update.update
    events:
      - http:
          path: definition/{id}
          method: put
          cors: true

  delete:
    handler: definition/delete.delete
    events:
      - http:
          path: definition/{id}
          method: delete
          cors: true

resources:
  Resources:
    DefinitionsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'definition'
